### ISSUE TITLE
How to deal with dynamically loaded images?

### ISSUE THREAD

**Issue by eikaramba** [aurelia/webpack-plugin#106]
I have the following code:

```
<div repeat.for="badge of user.badges" show.bind="badge.active">
    <img src="../../assets/images/${badge.image}">
</div>
```

When running webpack i get the following error:
`Error: Can't resolve '../../assets/images/${badge.image}'`

I guess because he is not able to resolve this during compile time. Shouldn't he ignore this in this case?
Also let's say he cannot automatically add the pictures to the bundle, how can i tell him to include these picture into the bundle?

* **Library Version:**
2.0.0-rc2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.8.0

* **NPM Version:**
4.4.0

* **JSPM OR Webpack AND Version**
webpack 2.3.3

* **Browser:**
all

* **Language:**
ESNext

**Comment by jods4** [comment]
This is purely webpack in action, specifically `html-loader`.
That loader looks at `src` attribute from `<img>` and creates dependencies for them.

Then Webpack complains because obviously `../../assets/images/${badge.image}` can't be resolved.

You can work around it in several ways:
- Use `src.bind` instead of interpolation;
- Don't process `img[src]` attributes at all with `attrs` option of `html-loader`;
- At that point `html-loader` is mostly useless, so you're probably better off with `raw-loader` instead.

**Comment by eikaramba** [comment]
Ah sry, i thought it does have to do with aurelia-webpack-plugin. Anyway the problem was that the files were not included in webpack and thus not accessible in any case. i fixed this by using:

```
new CopyWebpackPlugin([
      { from: 'src/assets/images/',to:'assets/images/' }
    ])
```
