### ISSUE TITLE
@inlineView dependencies not bundled

### ISSUE THREAD

**Issue by eikaramba** [aurelia/webpack-plugin#107]
I guess this is definitely a webpack-plugin issue ;)

In aurelia-materialize-bridge one of the view components is using an @inlineView Template which requires a css file (see this issue https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/401 and here the code https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/slider/slider.js)
```
@inlineView(`
  <template class="slider">
  <require from="./slider.css"></require>
  <ul class="slides">
    <slot></slot>
  </ul>
  </template>
`)
```

Unfortunately the slider.css dependency is not bundled, is that not handled yet?

**Comment by Thanood** [comment]
Sorry, I just changed that component to an html/js pair.
Here is the code as it was before:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/89d949bad5badb9e41fa3145fec5cb054609e589/src/slider/slider.js

**Comment by jods4** [comment]
Yes indeed. 

Not sure how to handle that, probably evaluate the string parameter of `inlineView` functions and run that through the `html-requires-loader` code.

**Comment by Thanood** [comment]
Btw. after using moduleName it seems like all the custom elements are bundled but no custom attributes. Of course I can create a separate issue for that.

**Comment by jods4** [comment]
@Thanood custom attributes are generally registered either: 
- locally with `<require from="..">` which should work if it's in a `.html` file.
- globally with a call to `.globalResource()` where you need to add a `PLATFORM.moduleName()` around the  parameter. If this is inside a 3rd party-lib that you can't modify, `ModuleDependenciesPlugin` is a work-around.

There is no specific knowledge of custom elements or custom attributes inside the Webpack plugin.

**Comment by Thanood** [comment]
@jods4 Thank you for your help and sorry for not being precise.. 😃 
In fact, I can modify the library in question.

This is the `src` directory of `aurelia-materialize-bridge` (only if you want an overview): https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/tree/master/src

The `globalResources` are built using a builder pattern in [config-builder](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/config-builder.js).

For example the `auto-complete` custom attribute is added like this:

```js
  useAutoComplete(): ConfigBuilder {
    this.globalResources.push('./autocomplete/autocomplete');
    return this;
  }
```

The `config-builder` creates an array which id used in `index.js`. It is [mapped](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/index.js#L20-L21) to provide `PLATFORM.moduleName()` to each array item defined in `config-builder`.

This is then loaded as an aurelia plugin..

```js
export function configure(aurelia, configCallback) {
  
  // ...

  if (builder.useGlobalResources) {
    const mappedResources = builder.globalResources.map(r => PLATFORM.moduleName(r));
    aurelia.globalResources(mappedResources);
  }
}
```

While this approach seems to work for custom elements as well as html-only components, it *seems* to fail for custom attributes.

Of course I may have done something wrong but I don't see it. 😃 

Just in case you want to try it yourself: This version is not yet published on `npm` but can be installed from its master branch.

I will try this again if I have some more time. 😃

**Comment by jods4** [comment]
You can't `globalResources.map(PLATFORM.moduleName)`.

`moduleName` is analyzed statically at build-time by Webpack to determine what needs to be included in your bundle. Dynamic code like shown above can't be analyzed.

You should wrap the strings when you push them:
```js
this.globalResources.push(PLATFORM.moduleName('./autocomplete/autocomplete'));
```

Caveats:
- Since it's a relative path, you need to do the push in the same folder as the module that will ultimately call `.globalResource()` at runtime.
- Even though users might not call `useAutoComplete()` and ultimately not use `./autocomplete/autocomplete` the module will still be included in the bundle.

That second point is implied by the fact that bundle contents are determined at build-time and there's no way Webpack can analyze JS to determine what code will run or not (so it assumes everything runs and every `moduleName` that is found gets included in the bundle).

If your goal is to be able to include in the bundle _just_ the modules that are used, you'll need alternative strategies.

One way is to repeat the configuration in the webpack config. Ultimately you'll want: 
```js
new ModuleDependenciesPlugin({
  'aurelia-materialize-bridge': ['./autocomplete/autocomplete', /* parts you actually use */ ]
})
```
This is how Aurelia does it for `.use.standardConfiguration()` and friends, see [`aureliaConfig` option](https://github.com/aurelia/webpack-plugin/wiki/AureliaPlugin-options#aureliaconfig).

Another way could be to have each `moduleName` in a separate module, maybe so:
```js
import { resources } from 'aurelia-materialize-bride';
resources.push(PLATFORM.moduleName('./autocomplete/autocomplete'));
```
And then ask users to create a module that lists what they want to use:
```js
import "aurelia-materialize-bridge/autocomplete";
import "aurelia-materialize-bridge/..."; // etc.
```
Since Webpack traces dependencies precisely, only the required modules end up included.

**Comment by Thanood** [comment]
@jods4 Thanks a lot for the thorough explanation. 👍 

I need to think about that because it's potentially changing my structure or even install process.
For now, I will use `moduleName` when I push the modules.

Isn't it interesting that it actually works with custom elements?

**Comment by jods4** [comment]
It is surprising! Maybe they're referenced by another mean?

**Comment by Thanood** [comment]
Not that I know of..
They're exported but attributes are, too. I don't know.. 😃

**Comment by niieani** [comment]
@jods4 awesome explanation [here](https://github.com/aurelia/webpack-plugin/issues/107#issuecomment-293878340). We should probably add it to your wiki (and docs).

**Comment by jods4** [comment]
RC-3 contains code that tries to detect resources inside `@inlineView('<template>')`.

The configuration (which tags/attributes) is shared with `html-requires-loader`. The only thing that is new is recognizing `inlineView` function calls.
