### ISSUE TITLE
[Feature request]: Enable loading css resources from view model

### ISSUE THREAD

**Issue by bigopon** [aurelia/webpack-plugin#132]
At the moment, doing the following is not working

```js
import {viewResources} from 'aurelia-framework'

@viewResources(PLATFORM.moduleName('./app.css'))
export class App {

}
```

This is for https://github.com/aurelia/templating/issues/581

**Comment by jods4** [comment]
First thing to check when it comes to loading CSS with Aurelia: [are your loaders properly configured?](https://github.com/aurelia/webpack-plugin/wiki/CSS-doesn't-load)

If answer is yes, it would be nice to provide a few details on the error you get or what is actually happening.

Generally speaking, there is no special considerations for this in Webpack plugin, so apart from your configuration there's a good chance that problems stem from the runtime.

**Comment by Alexander-Taran** [comment]
Hmm @bigopon can you clarify the difference with this approach and import './xxx.css'

**Comment by bigopon** [comment]
For following comparison:

In a custom element view, we can require css

```html
<template>
  <require from='some.css'></require>
</template>
```

Now if we do the same thing in custom attribute, it would be consistent, the way we load css resources. 

There is no issue with `import 'some.css'`, but it would make quite a puzzle for maintenance there, as why require here and there and import there and where ?

**Comment by Alexander-Taran** [comment]
@bigopon so to summarize it's kinda syntactic sugar. Right? no difference in produced result. I.e. css is not scoped shadowDommed.. or anything?

**Comment by bigopon** [comment]
kind of no. but we can always do some more work to scope it , if need be.

**Comment by Alexander-Taran** [comment]
well `newcomer` advocate in me says it won't be used by many.
It adds consistency in thinking about implementation details..
So you could achieve the same semantic meaning with decorator as with `require` tag
but nobody will know or find out. 
99.9% will end up with `import 'some.css'` anyway just because there are 100% more examples like this not specific to Aurelia

**Comment by doktordirk** [comment]
well, actually, i just checked if that would be possible. so, there would be some demand

**Comment by jods4** [comment]
I am closing this as there is no "feature" to add here.
I don't want to add magic and complexity inside the plugin, there's enough already.

Basically, this is about configuring your CSS loaders properly.
It's explained in details here: https://github.com/aurelia/webpack-plugin/wiki/CSS-doesn't-load

Note that if you use the suggested config:
```js
  rules: [
    {
      test: /\.css$/i,
      loader: 'css-loader',
      issuer: /\.html?$/i
    },
    {
      test: /\.css$/i,
      loader: ['style-loader', 'css-loader'],
      issuer: /\.[tj]s$/i
    }
  ]
```
Then it won't work because when the issuer is `.js` then `style-loader` is applied.
This is meant to make this code work:
```js
import "style.css";

export class VM {} 
```
But if you use 
```js
@viewResources(PLATFORM.moduleName("style.css")) 
export class VM { }
```
Then Aurelia is loading your CSS, even though it is references in a `.js`, and it expects plain CSS text, not a `style-loader` module.

Webpack provides many tools to control which loaders are applied in different situations. You need to play with that so that CSS loaders are applied in a way that matches how you use them.

For example, if you never import CSS directly and always go through Aurelia (either with `<require>` in view or `@viewResources` in js) you can just go with:
```js
  rules: [
    {
      test: /\.css$/i,
      loader: 'css-loader',
    },
  ]
```
This simple config will work for the code by OP.

If you have CSS imports in your `node_modules` (rather uncommon), you may want to apply different rules based on path.
