### ISSUE TITLE
Different templating language support

### ISSUE THREAD

**Issue by MrHayato** [aurelia/webpack-plugin#47]
We use Pug (formerly Jade) for our templates, and use a custom resource plugin and view locator to load them as templates. Webpack compiles the pug to html using pug-static-loader and the custom resource plugin just loads the template almost exactly the same as HTML templates. However, the webpack-plugin is only loading html files so it won't parse the require and compose elements in our pug files. This leads us to having to manually add every single component to `aurelia.build.resources` in package.json which is a headache, because we have many packages and modules.

In the older version of webpack-plugin, we had similar issues, but we were able to leverage the `includeSubModules` option that was available, to programmatically look through our project and automatically add our resources. However, we no longer have that option as it's been removed.

Can we get this option added back so we can inject our own resource location logic?

Also, on a sorta related note, another great feature would be able to alias our resources, similar to webpack alias. eg:

```
resources: [
  { alias: 'my-lib/my-awesome-component', path: 'my-lib/some-feature/components/my-awesome-component' }
]

// pug
template
  require(from="my-lib/my-awesome-component")
  my-awesome-component
```

**Comment by niieani** [comment]
Instead of adding `includeSubModules`, it would be better to allow for configurability regarding filetype resolution, separately for CSS resources, HTML resources and JS resources. Currently I've hardcoded:

- `.css`, `.sass`, `.less` as CSS resource extensions (this one done as path post-processing in `index.js`, as it requires a loader override), 
- `.js` and `.ts` as JavaScript resources
- `.html` as HTML template resources

As long as HTML template resources output raw HTML, the origin can be anything. Same goes for CSS source and JavaScript sources.
But if we have configurability, there's nothing stopping anybody from using, e.g. CoffeeScript or PureScript inside of Aurelia; or to compile HTML resources from any other template language.

If you'd like to propose an implementation, we'd be happy to merge it.

Aliases are currently implemented, but they only work to change the root directory of a module, e.g.:
```
aurelia: {
  build: {
    moduleRootOverride: [
      "aurelia-some-plugin": "dist/es2015"
    ]
  }
}
```

However, if we'd strip the resolved output paths to the last `node_modules` (instead of providing full, absolute paths), the plugin should honor Webpack's aliases. It already does so for pure root references like `aurelia-some-plugin`.

**Comment by jods4** [comment]
This works with the 2.x branch of webpack plugins.

To get it completely working there are several steps that you need to take:
1. Change the runtime policy to locate views (use `.pug` instead of `.html`) by modifying `ViewLocator.prototype.convertOriginToViewUrl`, see [this comment](https://github.com/aurelia/skeleton-navigation/issues/396#issuecomment-207823852) for an example that uses Jade templates.
2. Change the build-time policy to locate views by setting option `viewsExtensions: ['.pug', '.html']` (see [docs](https://github.com/jods4/aurelia-webpack-build/wiki/AureliaPlugin-options#viewfor-and-viewextensions)). Keeping `.html` in there is optional but might help in case you use libraries that include views by conventions (it's a bad practice for libraries, but it happens).
3. Make sure you set the proper loaders. In particular your HTML must go through `html-resources-loader`, so something like: `[ 'html-loader', 'html-resources-loader', 'pug-loader' ]`. That middle loader is generally taken care of by `AureliaPlugin` when you use `.html`, see [docs](https://github.com/jods4/aurelia-webpack-build/wiki/AureliaPlugin-options#nohtmlloader).

**Comment by niieani** [comment]
Just a small note, it would be good to add his to the wiki/docs.
