### ISSUE TITLE
includeDependencies does not seem to be working

### ISSUE THREAD

**Issue by istrau2** [aurelia/webpack-plugin#84]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
N/A

* **Language:**
ESNext

**Current behavior:**
I noticed that my app.bundle.js is really big today (4.3mb) so I decided to look at what was getting bundled. I noticed that all my dependencies (in package.json) were in there by default (not desirable). Instead I was hoping to only bundle resources that were explicitly imported from the entry file along with all aurelia resources. I tried using includeDependencies as specified in the docs:

```
"includeDependencies": "aurelia-*"
```
but it does not seem to be having any effect on the resulting bundle.

**Expected/desired behavior:**
I would like to only have the required dependencies bundled.

**Comment by EisenbergEffect** [comment]
Ping @niieani

**Comment by niieani** [comment]
`includeDependencies` feature was implemented by @andiriedl, perhaps he can give some feedback on why it might not work.

The problem you are describing is well known and a solution has already been designed. We will essentially be deprecating this plugin (aurelia-webpack-plugin) in favor of a more modular set of plugins where each one only does one thing and does it well (in the webpack-dependency-suite). 

A pre-alpha implementation that does not use this plugin is in the WIP PR https://github.com/aurelia/skeleton-navigation/pull/714. We are looking to merge this soon, definitely before the end of the year, maybe this or next week - can't say for sure since I've got a lot on my plate right now.

**Comment by niieani** [comment]
They didn't work cause the change wasn't released.
It was released with 1.2.0.

**Comment by istrau2** [comment]
@niieani Are there any plans to update the es-next-webpack skeleton with the latest versions of all the packages that we should be using (that is how I keep up with all the versions)?

**Comment by niieani** [comment]
@istrau2 All skeletons are kept up to date with all the latest versions that are supported by a given configuration. The Webpack skeletons almost all of the deps up-to-date.
