### ISSUE TITLE
Error loading 3rd party library that uses PLATFORM.moduleName()

### ISSUE THREAD

**Issue by swalters** [aurelia/webpack-plugin#96]
**I'm submitting a bug report**

* **Library Version:**
"aurelia-bootstrapper": "^2.1.0"
"aurelia-webpack-plugin": "^2.0.0-rc.1"

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.7

* **JSPM OR Webpack AND Version**
Webpack 2.2.0

* **Browser:**
Chrome 56 
* **Language:**
TypeScript 2.2.1

**Current behavior:**
Can recreate with https://github.com/swalters/agGridAureliaWebpack. This is a copy of @jods4 latest no_split demo

Error loading 3rd party library from node_modules.  Library ag-grid-aurelia in the referenced repository includes PLATFORM.moduleName() changes.

node_modules/ag-grid-aurelia/main.js
```
function configure(config) {
    config.globalResources(
      PLATFORM.moduleName('./lib/agGridAurelia'),
      PLATFORM.moduleName('./lib/agGridColumn'),
      PLATFORM.moduleName('./lib/agTemplate')
    );
}
```

Error is: Unable to find module with ID: ag-grid-aurelia/lib/agGridAurelia

**Comment by nashwaan** [comment]
Hi @jods4 ,

Any temp solution based on `ModuleDependenciesPlugin` for `ag-grid-aurelia` [similar to the solution for aurelia-i18n](https://github.com/jods4/aurelia-webpack-build/issues/18)?

I tried this:
```js
new ModuleDependenciesPlugin({
    'ag-grid-aurelia': ['./agGridAurelia']
})
```
but it didn't work.

**Comment by dvic** [comment]
For me this setup works:

```
new ModuleDependenciesPlugin({
        'ag-grid-aurelia': [
          './lib/agGridAurelia',
          './lib/agGridColumn',
          './lib/agTemplate'
        ]
    })
```

But will this be needed in the future? The whole idea of `PLATFORM.moduleName` was that modules can be reused without specifying dependencies right?

**Comment by jods4** [comment]
Yeah, when those deps are integrated into `ag-grid-aurelia` itself it should work out-of-the-box.
`ModuleDependenciesPlugin` is a stop-gap helper.

**Comment by nashwaan** [comment]
Thanks @dvic . That temporary solution worked for me.

**Comment by jods4** [comment]
@swalters I looked at your repro. You use a coding style that was not supported by the parser... with all the different module systems there are so many syntaxes to detect and handle :(

This is supported in RC1:
```js
let x = require("aurelia-pal");
x.PLATFORM.moduleName("id");
```
But you do this:
```js
let PLATFORM = require("aurelia-pal").PLATFORM;
PLATFORM.moduleName("id");`
```

You can change the syntax as indicated above, or wait for the RC2 that contains a few compat. improvements, including support for the syntax that you use above. I have opened PR aurelia/webpack-plugin#98 and hopefully Rob can publish it soon to NPM.

**Comment by istrau2** [comment]
@jods4 Can you expand on this statement:

> Yeah, when those deps are integrated into ag-grid-aurelia itself it should work out-of-the-box.
> ModuleDependenciesPlugin is a stop-gap helper.

What do you mean by integrated into the plugin. I am currently facing this issue with a number of plugins (Including some some that I, myself have written) and wondering what I can do. Thanks.

**Comment by jods4** [comment]
@istrau2 
Webpack traces the dependencies of each module and includes them in a bundle.
The problem with `aurelia-loader` is that it dynamically loads arbitrary stuff that Webpack doesn't know about -- and it doesn't work.
`PLATFORM.moduleName` documents those dependencies so that Webpack recognizes them and includes them in bundles.

A library typically does `.globalResources('./control')` in its plugin `configure()` function. 
As is, this results in a load that will fail.

The _work-around_ is to indicate the need for `control` to Webpack in your config with `ModuleDependenciesPlugin`.
The _better way_ is to modify the library to include a `PLATFORM.moduleName('./control')` call here. If you do so your users can just `.plugin(moduleName('your-lib'))` and that's it, everything just works.

In the end, the two produce _exactly the same result._ 
The first one must be done by each consumer of the lib and is hard to figure out.
The second one is done by the creator of the lib and then it just works.

**Comment by StrahilKazlachev** [comment]
@jods4 Any unwanted side effects if both are done?

**Comment by jods4** [comment]
no

**Comment by istrau2** [comment]
@jods4 I am having trouble using this logic for a feature. For example I am getting errors for this:
https://github.com/istrau2/lupoex-client/blob/feature/upgrade-skeleton/src/resources/resources.js

**Comment by jods4** [comment]
@istrau2 as I said in gitter, you can't do that: ` .map(r => PLATFORM.moduleName(r));` as `moduleName` is a marker that is analyzed at build-time so that Webpack can include the required dependencies in your bundle. So you need to wrap actual strings.

For a more complete discussion of that topic, see [this comment](https://github.com/aurelia/webpack-plugin/issues/107#issuecomment-293878340)

**Comment by nashwaan** [comment]
@jods4 or @swalters Although rc2 was released, I still cannot use `ag-grid-aurelia` out of the box. I can't get it to work without `ModuleDependenciesPlugin()`. Any update on this?

**Comment by jods4** [comment]
@nashwaan you might want to reach out to `ag-grid-aurelia` developpers about that?

**Comment by nashwaan** [comment]
@swalters , is there any problem that you are facing to update `ag-grid-aurelia` to make it work with the new `aurelia-webpack-plugin` (which is released officially)?

**Comment by swalters** [comment]
@nashwaan Time is my issue.  I have none to spare at the moment.  If you'd like to make a PR for the Platform.module support, I'll see that it gets merged.  Note that both the ag-grid-aurelia and ag-grid-aurelia-example should be updated

**Comment by nashwaan** [comment]
updating `ag-grid-aurelia` is as simple as making changes to 3 lines in `main.js`:

```js

exports.AgGridAurelia = require('./lib/agGridAurelia').AgGridAurelia;
exports.AgGridColumn = require('./lib/agGridColumn').AgGridColumn;
exports.AgCellTemplate = require('./lib/agTemplate').AgCellTemplate;
exports.AgEditorTemplate = require('./lib/agTemplate').AgEditorTemplate;
exports.AgFullWidthRowTemplate = require('./lib/agTemplate').AgFullWidthRowTemplate;
exports.AgFilterTemplate = require('./lib/agTemplate').AgFilterTemplate;
exports.AureliaCellRendererComponent = require('./lib/aureliaCellRendererComponent').AureliaCellRendererComponent;
exports.AureliaComponentFactory = require('./lib/aureliaComponentFactory').AureliaComponentFactory;
exports.AureliaFrameworkFactory = require('./lib/aureliaFrameworkFactory').AureliaFrameworkFactory;
exports.BaseAureliaEditor = require('./lib/editorViewModels').BaseAureliaEditor;

function configure(config) {
    config.globalResources(
      PLATFORM.moduleName('./lib/agGridAurelia'),  // wraping with PLATFORM.moduleName()
      PLATFORM.moduleName('./lib/agGridColumn'),   // wraping with PLATFORM.moduleName()
      PLATFORM.moduleName('./lib/agTemplate')      // wraping with PLATFORM.moduleName()
    );
}

exports.configure = configure;
```

Now loading `ag-grid-aurelia` plugin will work with `ModuleDependenciesPlugin()` hack!

Updating `ag-grid-aurelia-example` will require much work because every module referenced in:
* Routes { moduleId: "xxx" }
* .plugin("xxx")
* .feature("xxx") But see below!
* .globalResources("xxx")
* @useView("xxx")
* .setRoot("xxx")

should be updated to use PLATFORM.moduleName(). See [this ](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies)for more info. Also this example repo is based on aurelia cli which I am not familiar with (I use webpack).

But I believe it will not harm to update `ag-grid-aurelia` with the `PLATFORM.moduleName()` alone as this is backward compatible with previous codes, am I right on this @jods4 ?

**Comment by niieani** [comment]
Correct, moduleName is backwards compatible as it simply returns the string from the first parameter.

**Comment by nashwaan** [comment]
@swalters  Pull request https://github.com/ceolter/ag-grid-aurelia/pull/18 is submitted for the above suggested changes.

If this is accepted, then I hope the updated version of this package is published to npm sometime soon.
Thanks.

I will try later to update `ag-grid-aurelia-example` repo.

**Comment by swalters** [comment]
@nashwaan your PR fails to work.  You did not import the PLATFORM variable into main.js.

You can test any PR by doing 'npm run build' on your change and then copy the project to your node_modules or you can configure your package.json to pull the package from your local repository.

**Comment by nashwaan** [comment]
Fixed the PR and glad it is accepted. Waiting for it to be published into npm.
😏
